{{- define "job" -}}
backoffLimit: {{ .Values.backoffLimit }}
activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
template:
  metadata:
    labels:
      app: {{ template "helper.name" . }}
      release: {{ .Release.Name }}
  spec:
    serviceAccountName: {{ template "helper.fullname" . }}
    containers:
    - name: {{ template "helper.fullname" . }}
      image: {{ template "helper.image" . }}
      env:
      - name: ACME_MANAGE_ALL_NAMESPACES
        value: {{ .Values.manageAllNamespaces | quote }}
      - name: ACME_NAMESPACES_WHITELIST
        value: {{ .Values.namespacesWhitelist | quote }}
      - name: ACME_DEMO_ENABLED
        value: {{ .Values.demo.enabled | quote }}
      - name: ACME_DEBUG
        value: {{ .Values.debug | quote }}
      {{- range $k, $v := .Values.env }}
      - name: {{ $k | quote }}
        value: {{ $v | quote }}
      {{- end }}
    restartPolicy: Never
{{- end -}}
