{{- if .Values.manageAllNamespaces -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "helper.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "helper.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ template "helper.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}