apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
    app: {{ template "helper.name" . }}
    chart: {{ template "helper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: {{ template "helper.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- include "job" . | nindent 6 }}
