apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
    app: {{ template "helper.name" . }}
    chart: {{ template "helper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- include "job" . | nindent 2 }}
