apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
---
{{- if .Values.manageAllNamespaces -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "helper.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ template "helper.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- if not .Values.manageAllNamespaces -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "helper.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ template "helper.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
