{{- if not .Values.manageAllNamespaces -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "helper.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "create", "patch"]
  {{- if gt (len .Values.secretResourceNames) 0 }}
  resourceNames:
  {{- range .Values.secretResourceNames }}
    - {{ . | quote }}
    - {{ printf "%s-conf" . | quote }}
  {{- end }}  
  {{- end }}
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list"]
{{- end -}}
